### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by corq** [sgtStrom/AllRetweetsBot#6] opened 2017-11-13 15:24 UTC
Seems to not break the app but now retweets never occur after this message is seen -  python 3.4 at issue? I'm unfamilar with this particular message. 

```
2017-11-13 15:21:08,753 INFO Getting last Monday's stats...
Exception in thread t_statsmaker:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/opt/AllRetweetsBot/libbot.py", line 298, in run
    followers_old_s = cur.fetchone()[1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by sgtStrom** [comment] 2017-11-18 09:50
Seems like database doesn't have any records of previous followers count and `cur.fetchone()` is None, not a list. I'll fix this bug now.

Actually, the code is quite raw, if an exception that the bot couldn't catch in try...except clause occurs, it won't retweet anymore. I'm going to re-organize these moments soon. That'll be (I hope) version 1.0 :)

**Comment by sgtStrom** [comment] 2017-11-18 10:01
Fixed it. Please, git pull and check.

**Comment by sgtStrom** [comment] 2017-11-28 14:01
No answer. I am not able to reproduce this bug, so close it now.

**Closed by sgtStrom** 2017-11-28 14:01 UTC
Labels: bug
